# Generated by Django 3.0.8 on 2020-09-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortApp', '0002_auto_20200904_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Job',
            field=models.CharField(default='', max_length=100),
        ),
    ]
