# Generated by Django 3.0.8 on 2020-09-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortApp', '0003_article_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Date',
            field=models.DateField(default=''),
        ),
    ]
