# Generated by Django 3.0.8 on 2020-09-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortApp', '0004_article_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Date',
        ),
    ]
